### PR TITLE
RFC 7233 (range requests)

### PR DESCRIPTION
**Pull request by regular**
Hey @dominictarr , I implemented HTTP1.1 range requests (RFC 7233) for blobs.

I needed this to better support video playback. Browsers tend to refuse to loop videos otherwise and seeking in videos requires range requests. It's also great for extracting embedded thumbnails from JPEGs etc.

I added tests including for the old functionality (there were none)

### CODE REVIEW

**Comment by dominictarr** [comment]
This is awesome!!!
I love your PRs there are always tests!

Merged into 1.0.0, and also released ssb-ws@6.2.0 to use this.

**Comment by dominictarr** [comment]
oh I also added a little bit of docs, so that there is a link to the rfc.

> It's also great for extracting _embedded thumbnails from JPEGs_ etc.

I did not know you could embed a thumbnail in a jpg!

**Comment by regular** [comment]
:) Thank you, @dominictarr , I love your code too!

> I did not know you could embed a thumbnail in a jpg!

Cameras do that. Probably to reduce their own processing time when displaying a super high-res image on their low res display. EXIF data gives you offset, length and type of the embedded thumbnail.

**Comment by regular** [comment]
@dominictarr how do you feel about publishing this as 0.5.0? The way you did it now (1.0.0) prevents it from being picked up by older versions of ssb-ws (which is a bummer, because I am using an older version of ssb-ws, I am on sbot 11.3.x). After all, it's not a breaking change but a feature addition.

0.5.0 and 1.0.0 being identical would be a bit weird, but should cause no harm, I guess?

**Pull request merged**
